import { AffiliateLevel } from "./types/AffiliateLevel";
import AffiliateLevelCard from "./AffiliateLevelCard/AffiliateLevelCard";
import { FaClock, FaMoneyBillWave, FaUserPlus } from "react-icons/fa";
import Header from "../../../components/Header/Header";

const levels: AffiliateLevel[] = [
  {
    title: "🥇 Nivel 1",
    range: "1 a 10 referidos",
    percentage: 10,
    toleranceDays: 5,
    rules: [
      {
        icon: <FaUserPlus />,
        name: "Afiliá entre 1 y 10 personas.",
      },
      {
        icon: <FaMoneyBillWave />,
        name: "Cobrás el 10% de cada depósito de tus referidos.",
      },
      {
        icon: <FaClock />,
        name: "Tus referidos tienen 5 días para volver a depositar.",
      },
    ],
    examples: [
      { name: "Ana Fernández", deposit: 5000 },
      { name: "Pedro Sánchez", deposit: 9500 },
      { name: "Laura Martínez", deposit: 6000 },
      { name: "Juan Pérez", deposit: 3000 },
      { name: "Carlos Díaz", deposit: 2000 },
      { name: "Lucía Gómez", deposit: 9000 },
      { name: "José Ramírez", deposit: 2000 },
      { name: "Laura Martínez", deposit: 4000 },
      { name: "Sofía López", deposit: 2000 },
      { name: "Pedro Sánchez", deposit: 5000 },
      { name: "Diego González", deposit: 4000 },
      { name: "María Torres", deposit: 1000 },
      { name: "José Ramírez", deposit: 500 },
      { name: "Lucía Gómez", deposit: 5000 },
      { name: "Pedro Sánchez", deposit: 7000 },
      { name: "Juan Pérez", deposit: 7000 },
      { name: "Sofía López", deposit: 1000 },
      { name: "Laura Martínez", deposit: 5000 },
      { name: "Diego González", deposit: 3000 },
      { name: "Pedro Sánchez", deposit: 8000 },
      { name: "Ana Fernández", deposit: 6000 },
      { name: "Diego González", deposit: 6500 },
      { name: "Pedro Sánchez", deposit: 4000 },
      { name: "Lucía Gómez", deposit: 1000 },
      { name: "José Ramírez", deposit: 1500 },
      { name: "Lucía Gómez", deposit: 2000 },
      { name: "Juan Pérez", deposit: 5000 },
      { name: "María Torres", deposit: 7000 },
      { name: "María Torres", deposit: 3000 },
      { name: "Lucía Gómez", deposit: 3000 },
      { name: "Pedro Sánchez", deposit: 3000 },
      { name: "José Ramírez", deposit: 1000 },
      { name: "María Torres", deposit: 5000 },
      { name: "Diego González", deposit: 1000 },
      { name: "Diego González", deposit: 2000 },
    ],
  },
  {
    title: "🥈 Nivel 2",
    range: "11 a 30 referidos",
    percentage: 12,
    toleranceDays: 7,
    rules: [
      {
        icon: <FaUserPlus />,
        name: "Afiliá entre 11 y 30 personas.",
      },
      {
        icon: <FaMoneyBillWave />,
        name: "Cobrás el 12% de cada depósito de tus referidos.",
      },
      {
        icon: <FaClock />,
        name: "Tus referidos tienen 7 días para volver a depositar.",
      },
    ],
    examples: [
      { name: "Juan Pérez", deposit: 3000 },
      { name: "Juan Pérez", deposit: 5000 },
      { name: "Lucía Gómez", deposit: 9000 },
      { name: "Lucía Gómez", deposit: 7000 },
      { name: "Carlos Díaz", deposit: 2000 },
      { name: "Carlos Díaz", deposit: 3000 },
      { name: "Carlos Díaz", deposit: 5000 },
      { name: "María Torres", deposit: 7000 },
      { name: "José Ramírez", deposit: 500 },
      { name: "Ana Fernández", deposit: 6000 },
      { name: "Pedro Sánchez", deposit: 9500 },
      { name: "Laura Martínez", deposit: 5000 },
      { name: "Sofía López", deposit: 1000 },
      { name: "Sofía López", deposit: 3000 },
      { name: "Diego González", deposit: 6500 },
      { name: "Martín Castro", deposit: 3000 },
      { name: "Martín Castro", deposit: 7000 },
      { name: "Martín Castro", deposit: 9000 },
      { name: "Valentina Rojas", deposit: 4000 },
      { name: "Valentina Rojas", deposit: 5000 },
      { name: "Gabriel Herrera", deposit: 3000 },
      { name: "Gabriel Herrera", deposit: 6000 },
      { name: "Gabriel Herrera", deposit: 2000 },
      { name: "Gabriel Herrera", deposit: 7000 },
      { name: "Elena Vega", deposit: 9000 },
      { name: "Elena Vega", deposit: 2000 },
      { name: "Elena Vega", deposit: 1000 },
      { name: "Santiago Morales", deposit: 8000 },
      { name: "Santiago Morales", deposit: 5000 },
      { name: "Santiago Morales", deposit: 2000 },
      { name: "Emilia Bravo", deposit: 4000 },
      { name: "Emilia Bravo", deposit: 6000 },
      { name: "Emilia Bravo", deposit: 9000 },
      { name: "Emilia Bravo", deposit: 3000 },
      { name: "Emilia Bravo", deposit: 1000 },
      { name: "Franco Acosta", deposit: 5000 },
      { name: "Franco Acosta", deposit: 2000 },
      { name: "Franco Acosta", deposit: 8000 },
      { name: "Franco Acosta", deposit: 9000 },
      { name: "Mateo López", deposit: 7000 },
      { name: "Mateo López", deposit: 1000 },
      { name: "Mateo López", deposit: 3000 },
      { name: "Mateo López", deposit: 4000 },
      { name: "Camila Torres", deposit: 5000 },
      { name: "Camila Torres", deposit: 2000 },
      { name: "Camila Torres", deposit: 8000 },
      { name: "Agustín Romero", deposit: 6000 },
      { name: "Agustín Romero", deposit: 9000 },
      { name: "Agustín Romero", deposit: 4000 },
      { name: "Martina Herrera", deposit: 7000 },
      { name: "Martina Herrera", deposit: 3000 },
      { name: "Martina Herrera", deposit: 5000 },
      { name: "Felipe Vargas", deposit: 9000 },
      { name: "Felipe Vargas", deposit: 6000 },
      { name: "Felipe Vargas", deposit: 7000 },
      { name: "Isabella Reyes", deposit: 4000 },
      { name: "Isabella Reyes", deposit: 5000 },
      { name: "Isabella Reyes", deposit: 2000 },
      { name: "Tomás Méndez", deposit: 1000 },
      { name: "Tomás Méndez", deposit: 3000 },
      { name: "Tomás Méndez", deposit: 4000 },
    ],
  },

  {
    title: "🥉 Nivel 3",
    range: "31 o más referidos",
    percentage: 15,
    toleranceDays: 10,
    rules: [
      {
        icon: <FaUserPlus />,
        name: "Afiliá 31 personas o más.",
      },
      {
        icon: <FaMoneyBillWave />,
        name: "Cobrás el 15% de cada depósito de tus referidos.",
      },
      {
        icon: <FaClock />,
        name: "Tus referidos tienen 10 días para volver a depositar.",
      },
    ],
    examples: [
      { name: "Juan Pérez", deposit: 5000 },
      { name: "Juan Pérez", deposit: 3000 },
      { name: "Juan Pérez", deposit: 7000 },
      { name: "Lucía Gómez", deposit: 8000 },
      { name: "Lucía Gómez", deposit: 9000 },
      { name: "Lucía Gómez", deposit: 1000 },
      { name: "Lucía Gómez", deposit: 2000 },
      { name: "Carlos Díaz", deposit: 4000 },
      { name: "Carlos Díaz", deposit: 5000 },
      { name: "Carlos Díaz", deposit: 6000 },
      { name: "Carlos Díaz", deposit: 2000 },
      { name: "María Torres", deposit: 3000 },
      { name: "María Torres", deposit: 3000 },
      { name: "José Ramírez", deposit: 1000 },
      { name: "Ana Fernández", deposit: 4000 },
      { name: "Ana Fernández", deposit: 5000 },
      { name: "Pedro Sánchez", deposit: 7000 },
      { name: "Pedro Sánchez", deposit: 10000 },
      { name: "Laura Martínez", deposit: 3000 },
      { name: "Laura Martínez", deposit: 4000 },
      { name: "Sofía López", deposit: 2000 },
      { name: "Sofía López", deposit: 1000 },
      { name: "Sofía López", deposit: 5000 },
      { name: "Diego González", deposit: 6000 },
      { name: "Diego González", deposit: 6000 },
      { name: "Martín Castro", deposit: 3000 },
      { name: "Martín Castro", deposit: 7000 },
      { name: "Valentina Rojas", deposit: 4000 },
      { name: "Gabriel Herrera", deposit: 6000 },
      { name: "Gabriel Herrera", deposit: 2000 },
      { name: "Elena Vega", deposit: 9000 },
      { name: "Elena Vega", deposit: 7000 },
      { name: "Santiago Morales", deposit: 8000 },
      { name: "Emilia Bravo", deposit: 4000 },
      { name: "Franco Acosta", deposit: 5000 },
      { name: "Franco Acosta", deposit: 4000 },
      { name: "Mateo López", deposit: 7000 },
      { name: "Camila Torres", deposit: 5000 },
      { name: "Agustín Romero", deposit: 6000 },
      { name: "Martina Herrera", deposit: 7000 },
      { name: "Felipe Vargas", deposit: 9000 },
      { name: "Isabella Reyes", deposit: 4000 },
      { name: "Tomás Méndez", deposit: 1000 },
      { name: "Tomás Méndez", deposit: 2000 },
      { name: "Santiago Paredes", deposit: 3500 },
      { name: "Antonella Bustos", deposit: 7000 },
      { name: "Lucas Castillo", deposit: 4000 },
      { name: "Melina Benítez", deposit: 8500 },
      { name: "Bruno Domínguez", deposit: 6000 },
      { name: "Jazmín Toledo", deposit: 5000 },
      { name: "Matías Correa", deposit: 9000 },
      { name: "Renata Molina", deposit: 7000 },
      { name: "Lautaro Ibáñez", deposit: 2000 },
      { name: "Victoria Ponce", deposit: 7500 },
      { name: "Thiago Sosa", deposit: 4500 },
      { name: "Paulina Aguirre", deposit: 8000 },
      { name: "Federico Figueroa", deposit: 5000 },
      { name: "Aitana Medina", deposit: 6000 },
      { name: "Benjamín Núñez", deposit: 7000 },
      { name: "Martina Silva", deposit: 3000 },
      { name: "Ignacio Rivas", deposit: 4000 },
      { name: "Julieta Navarro", deposit: 6500 },
      { name: "Nicolás Vera", deposit: 5000 },
      { name: "Valeria Franco", deposit: 8000 },
      { name: "Damián Rojas", deposit: 5500 },
      { name: "Catalina Muñoz", deposit: 7000 },
      { name: "Lucas Gómez", deposit: 4000 },
      { name: "Abril Sánchez", deposit: 3000 },
      { name: "Francisco Herrera", deposit: 9000 },
      { name: "Camila Bustamante", deposit: 8000 },
      { name: "Emiliano Ortiz", deposit: 7000 },
      { name: "Tatiana Maldonado", deposit: 6000 },
      { name: "Julián Morales", deposit: 5000 },
      { name: "Noelia Álvarez", deposit: 4000 },
      { name: "Leandro Salinas", deposit: 2000 },
      { name: "Paula Cabrera", deposit: 1000 },
    ],
  },
];

const AffiliateProgram = () => {
  return (
    <>
      <h1 style={{ color: "var(--title-pink)", textAlign: "center" }}>
        Conecta y ganá
      </h1>
      {levels.map((level, i) => (
        <AffiliateLevelCard key={i} level={level} />
      ))}

      <Header />
    </>
  );
};

export default AffiliateProgram;
